apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-48w8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-48w8
    app.kubernetes.io/part-of: tkrw-pr712-0075-0035-app
  name: devfile-sample-48w8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-48w8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-48w8
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-48w8@sha256:47cdfc0c2f9338c21e0fafc76277ce24f471331ccd7b3e50d7027c92dc081d65
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
