apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-48w8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-48w8@sha256:47cdfc0c2f9338c21e0fafc76277ce24f471331ccd7b3e50d7027c92dc081d65
        name: my-nodejs
        resources: {}
status: {}
